#include "VsrEngine.h"
#include "HexText.h"
#include "Log.h"
#include "NgxSession.h"
#ifdef DLSS_VIDEO_PLAYER_HAS_RTX_VSR
// Generated by CMake from -DRTX_VIDEO_SDK: the DLSS SDK's helpers first, then the
// RTX Video SDK's VSR helpers by absolute path. The VSR SDK carries its own copies
// of the NGX core headers under the same include guards, so the DLSS SDK's - the
// ones the linked core was built from - are the ones that stay in force. The SDK's
// inline helpers name a parameter they never read (C4100), which /W4 /WX would
// refuse in a header this project does not own; the analyzer configuration already
// treats them as external (/external:anglebrackets).
#pragma warning(push, 0)
#include "RtxVideoSdkHeaders.h"
#pragma warning(pop)
#endif

VsrEngine::~VsrEngine() { Shutdown(); }

#ifdef DLSS_VIDEO_PLAYER_HAS_RTX_VSR

void VsrEngine::Probe(ID3D12Device* device)
{
    if (m_probed) return;
    m_probed = true;
    IUnknown* identity = nullptr;
    if (!device || FAILED(device->QueryInterface(IID_IUnknown, reinterpret_cast<void**>(&identity)))) {
        LOG("RTX VSR: no device identity; the view is unavailable.");
        return;
    }
    const void* key = identity;
    identity->Release();
    // Join, never start: a device with no lease is one NGX never started on.
    if (!ngx_session_detail::ProcessRegistry().Acquire(key, [] { return false; })) {
        LOG("RTX VSR: no NGX session on this device; the view is unavailable.");
        return;
    }
    m_device = device;
    m_sessionKey = key;
    m_caps.session = true;
    m_lastResult = NVSDK_NGX_D3D12_GetCapabilityParameters(&m_params);
    if (NVSDK_NGX_FAILED(m_lastResult) || !m_params) {
        m_params = nullptr;
        LOG("RTX VSR: GetCapabilityParameters failed result=" << HexText(m_lastResult));
        return;
    }
    m_caps.queried = true;
    int available = 0, needsDriver = 0;
    unsigned int major = 0, minor = 0;
    const NVSDK_NGX_Result availableResult = NVSDK_NGX_Parameter_GetI(m_params, NVSDK_NGX_Parameter_VSR_Available, &available);
    m_caps.availableRead = !NVSDK_NGX_FAILED(availableResult);
    m_caps.available = m_caps.availableRead && available != 0;
    if (!NVSDK_NGX_FAILED(NVSDK_NGX_Parameter_GetI(m_params, NVSDK_NGX_Parameter_VSR_NeedsUpdatedDriver, &needsDriver)))
        m_caps.needsUpdatedDriver = needsDriver != 0;
    if (!NVSDK_NGX_FAILED(NVSDK_NGX_Parameter_GetUI(m_params, NVSDK_NGX_Parameter_VSR_MinDriverVersionMajor, &major)))
        m_caps.minDriverMajor = major;
    if (!NVSDK_NGX_FAILED(NVSDK_NGX_Parameter_GetUI(m_params, NVSDK_NGX_Parameter_VSR_MinDriverVersionMinor, &minor)))
        m_caps.minDriverMinor = minor;
    int initResult = 0;
    const bool initRead = !NVSDK_NGX_FAILED(NVSDK_NGX_Parameter_GetI(m_params, NVSDK_NGX_Parameter_VSR_FeatureInitResult, &initResult));
    LOG("RTX VSR capability: Available=" << (m_caps.availableRead ? std::to_string(available) : "unreadable " + HexText(availableResult))
        << " NeedsUpdatedDriver=" << needsDriver << " MinDriver=" << major << "." << minor
        << " FeatureInitResult=" << (initRead ? HexText(static_cast<uint32_t>(initResult)) : std::string("unreadable")));
}

bool VsrEngine::CreateFeature(ID3D12GraphicsCommandList* cmd)
{
    if (m_handle) return true;
    if (!cmd || !m_params || Reason() != vsr_policy::Reason::Ready || m_caps.createAttempted) return false;
    m_caps.createAttempted = true;
    // Single-GPU node masks, as DLSSBackend's create sets them.
    NVSDK_NGX_Parameter_SetUI(m_params, NVSDK_NGX_Parameter_CreationNodeMask, 1);
    NVSDK_NGX_Parameter_SetUI(m_params, NVSDK_NGX_Parameter_VisibilityNodeMask, 1);
    m_lastResult = NVSDK_NGX_D3D12_CreateFeature(cmd, NVSDK_NGX_Feature_VSR, m_params, &m_handle);
    if (NVSDK_NGX_FAILED(m_lastResult) || !m_handle) {
        m_handle = nullptr;
        LOG("RTX VSR CreateFeature failed result=" << HexText(m_lastResult) << "; the view is unavailable.");
        return false;
    }
    m_caps.createSucceeded = true;
    LOG("RTX VSR feature created (NGX feature 16).");
    return true;
}

bool VsrEngine::Evaluate(ID3D12GraphicsCommandList* cmd, ID3D12Resource* input, uint32_t inputW, uint32_t inputH,
                         ID3D12Resource* output, uint32_t outputW, uint32_t outputH, vsr_policy::Quality quality)
{
    if (!m_handle || !m_params || !cmd || !input || !output || !inputW || !inputH || !outputW || !outputH) return false;
    NVSDK_NGX_D3D12_VSR_Eval_Params eval{};
    eval.pInput = input;
    eval.pOutput = output;
    eval.InputSubrectBase = {0, 0};
    eval.InputSubrectSize = {inputW, inputH};
    eval.OutputSubrectBase = {0, 0};
    eval.OutputSubrectSize = {outputW, outputH};
    eval.QualityLevel = static_cast<NVSDK_NGX_VSR_QualityLevel>(static_cast<int>(quality));
    m_lastResult = NGX_D3D12_EVALUATE_VSR_EXT(cmd, m_handle, m_params, &eval);
    if (NVSDK_NGX_FAILED(m_lastResult)) {
        LOG("RTX VSR Evaluate failed result=" << HexText(m_lastResult) << " input=" << inputW << "x" << inputH
            << " output=" << outputW << "x" << outputH << " quality=" << static_cast<int>(quality));
        return false;
    }
    ++m_evaluations;
    if (m_evaluations == 1)
        LOG("RTX VSR first evaluate: input=" << inputW << "x" << inputH << " output=" << outputW << "x" << outputH
            << " quality=" << static_cast<int>(quality));
    return true;
}

void VsrEngine::Shutdown()
{
    if (m_handle) {
        NVSDK_NGX_D3D12_ReleaseFeature(m_handle);
        m_handle = nullptr;
    }
    if (m_params) {
        NVSDK_NGX_D3D12_DestroyParameters(m_params);
        m_params = nullptr;
    }
    if (m_sessionKey) {
        // Normally DLSSBackend still holds the session and this only drops the
        // count; were it gone first, the last one out shuts NGX down as it would.
        ID3D12Device* device = m_device;
        ngx_session_detail::ProcessRegistry().Release(m_sessionKey, [device] { NVSDK_NGX_D3D12_Shutdown1(device); });
        m_sessionKey = nullptr;
    }
    m_device = nullptr;
}

#else

// Built without the RTX Video SDK: there is no engine to ask, and the view says so.
void VsrEngine::Probe(ID3D12Device*) { m_probed = true; }
bool VsrEngine::CreateFeature(ID3D12GraphicsCommandList*) { return false; }
bool VsrEngine::Evaluate(ID3D12GraphicsCommandList*, ID3D12Resource*, uint32_t, uint32_t, ID3D12Resource*, uint32_t, uint32_t,
                         vsr_policy::Quality)
{
    return false;
}
void VsrEngine::Shutdown() {}

#endif
